In [2]:
import os
directory_path = 'C50testshort'

for root, dirs, files in os.walk(directory_path):

    for author in dirs:
        author = os.path.join(root, author)
        print(f"currauthor: {author}")
        txtfiles = os.listdir(author)
        print(f"Files writtenby {author}: {txtfiles}")

        for file in txtfiles:
            file_path = os.path.join(author, file)
            with open(file_path, 'r') as curr:
                file_content = curr.read()
                print(file_content)



currauthor: C50testshort/AaronPressman
Files writtenby C50testshort/AaronPressman: ['492068newsML.txt', '517526newsML.txt', '606238newsML.txt', '469448newsML.txt', '635785newsML.txt', '421829newsML.txt', '466275newsML.txt', '491060newsML.txt', '42764newsML.txt', '593702newsML.txt', '450788newsML.txt', '479564newsML.txt', '424074newsML.txt', '544012newsML.txt', '602453newsML.txt', '600865newsML.txt', '493995newsML.txt', '539259newsML.txt', '494466newsML.txt', '593715newsML.txt', '582759newsML.txt', '482034newsML.txt', '433558newsML.txt', '518507newsML.txt', '507230newsML.txt', '601962newsML.txt', '492770newsML.txt', '439561newsML.txt', '436774newsML.txt', '653225newsML.txt', '486982newsML.txt', '629404newsML.txt', '650163newsML.txt', '43033newsML.txt', '478157newsML.txt', '605443newsML.txt', '582927newsML.txt', '630942newsML.txt', '581517newsML.txt', '637021newsML.txt', '566383newsML.txt', '496933newsML.txt', '608287newsML.txt', '583229newsML.txt', '602451newsML.txt', '491643newsML.txt'

In [3]:
import re


In [6]:
from nltk.stem.snowball import SnowballStemmer
import numpy as np

stem = True
stop = True
stop_set = {}
stemmer = SnowballStemmer('english')
vocab = {} #going to be of the form {word:[f1, .., fn]} where each f_i is how many times that word appears in document i
#therefore the wordset is just all the keys of the document
size = 2500
file = "testdoc.txt"

ground_tru = [()] * size

i = 0
for author in dirs: #name of dir, in this case the author

    #irrelevant
    author = os.path.join(root, author)
    txtfiles = os.listdir(author)
    

    for file in txtfiles:
        ground_tru[i] = (file, author)#assigns ground truth value
        with open(file, 'r') as curr:
            text = curr.read()
            words = split_txt(text) #will be list of words, no punctuation except apostrophes

            for word in words:
                word = word.lower()
                #big decision whether we stem first or stop first, can determine later
                if stem:
                    word = stemmer.stem(word) #modifies word essentially changes to short version

                if stop and word in stop_set: #checks if stopping is true and then if in stop set
                    continue #skips word


                if word not in vocab:
                    vocab[word] = np.zeros(size)

                vocab[word][i] += 1

                i += 1

return vocab, ground_tru
            
            




SyntaxError: 'return' outside function (1955051091.py, line 46)

In [ ]:
import csv
def write_truth(path, list_in): #assumes path is path name, list_in is nested list of ground truths
# of the form [(txtdoc, author),....]

    # Write the nested list to the CSV file
    with open(path, mode="w", newline="") as csv_file:
        csv_writer = csv.writer(csv_file)
        csv_writer.writerows(list_in)

['This', 'is', 'an', 'example', 'sentence', 'with', 'some', 'punctuation', 'and', 'spaces', "It's", 'a', 'test']


In [ ]:
file_content = file.read()

# Create a set of unique words
word_set = set(file_content.split())


In [ ]:
ground_tru = [()] *1000


In [ ]:
name = "testdoc.txt"


os.path.exists(name)

True

In [7]:
import numpy as np
test = {"t":np.zeros(100)}
test["t"][3] += 1
test["t"]

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
def generate_symmetric_distance_matrix(size):
    # Generate a random square matrix
    matrix = np.random.rand(size, size)
    
    # Make it symmetric by taking the average with its transpose
    sym_matrix = (matrix + matrix.T) / 2
    
    # Set the diagonal to zero (distance from an element to itself)
    np.fill_diagonal(sym_matrix, 0)
    
    return sym_matrix

# Specify the size of the matrix
matrix_size = 3  # Replace with your desired size

# Generate a random symmetric square distance matrix
distance_matrix = generate_symmetric_distance_matrix(5)

print(distance_matrix)


[[0.         0.56857109 0.48276605 0.3723078  0.78238489]
 [0.56857109 0.         0.65323254 0.49334173 0.41736818]
 [0.48276605 0.65323254 0.         0.39416086 0.89435223]
 [0.3723078  0.49334173 0.39416086 0.         0.34327775]
 [0.78238489 0.41736818 0.89435223 0.34327775 0.        ]]


In [11]:
np.count_nonzero(distance_matrix[:,3])

4

In [ ]:
k = 2
for row in distance_matrix:
    np.argsort(row)[1:k+1]

[1 3]
[3 4]
[4 1]
[1 0]
[2 1]


In [ ]:
import pandas as pd
data = {'Column1': [1, 2, 2, 3, 3, 3, 4, 4, 4, 4],
        'C': ['A', 'B', 'A', 'B', 'A', 'C', 'C', 'A', 'B', 'C']}
df = pd.DataFrame(data)


In [ ]:
a = df["C"].unique()
b = df["C"]
test = pd.Categorical(b, categories=a)
test

['A', 'B', 'A', 'B', 'A', 'C', 'C', 'A', 'B', 'C']
Categories (3, object): ['A', 'B', 'C']

In [13]:


import numpy as np

# Create a sample NumPy matrix
matrix = np.array([1,3,5,6])

# Find the maximum value in each row
a = np.max(matrix)
10 / a


1.6666666666666667